# Generated by Django 6.0.3 on 2026-03-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_userprofile_is_deleted_alter_userprofile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
