# Generated by Django 6.0.3 on 2026-03-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_userprofile_email_is_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="email_is_verified",
        ),
    ]
