# Generated by Django 6.0.3 on 2026-03-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_remove_userprofile_email_is_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="hexalearn_profile_pics/"
            ),
        ),
    ]
