# Generated by Django 6.0.3 on 2026-03-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
