services:
  hexalearn_aws:
    build: .
    container_name: hexalearn_aws
    user: root
    restart: always
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - .env
    command: ["/app/entrypoint.prod.sh"]
 
  frontend_proxy:
    image: nginx:alpine          # alpine nhẹ hơn nginx:latest ~50MB
    container_name: hexalearn_aws_nginx
    ports:
      - "8001:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
    depends_on:
      - hexalearn_aws
    restart: always
 
volumes:
  static_volume: