# Generated by Django 6.0.3 on 2026-03-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dict", "0002_alter_kanjiword_unique_together_and_more"),
        ("home", "0009_alter_userprofile_native_language"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="word",
            index=models.Index(fields=["lemma"], name="dict_word_lemma_91fb41_idx"),
        ),
        migrations.AddIndex(
            model_name="wordmeaning",
            index=models.Index(
                fields=["short_definition"], name="dict_wordme_short_d_2a50ee_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wordpronunciation",
            index=models.Index(
                fields=["pronunciation"], name="dict_wordpr_pronunc_62f53c_idx"
            ),
        ),
    ]
