# Generated by Django 6.0.3 on 2026-03-22 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deck", "0003_folder_deck_folder"),
        ("home", "0007_alter_level_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="estimated_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decks",
                to="home.level",
            ),
        ),
        migrations.AlterField(
            model_name="deck",
            name="source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="decks",
                to="home.source",
            ),
        ),
    ]
